### ISSUE TITLE
简历项目建议

### ISSUE THREAD

**Issue by genalhuang** [yooabe/Resume#1]
1. 加一下新功能杂志搜索/杂志详情
2. 收藏可以用一个红心按钮替代 未收藏红心是灰色
3. 计算器太简单了...

**Comment by yooabe** [comment]
1、2点当时想做来着，因为时间跟技术原因就搁置了。计算器是凑数的，现在要把它删了。
感谢大佬的建议，我决定花点时间把前两个项目改进一下再战

**Comment by yooabe** [comment]
> 1. 加一下新功能杂志搜索/杂志详情
> 2. 收藏可以用一个红心按钮替代 未收藏红心是灰色
> 3. 计算器太简单了...
